### ISSUE TITLE
Trying to connect through OIDC with Authentik

### ISSUE THREAD

**Issue by LeVraiRoiDHyrule** [heviat/Mailu-OIDC#36]
### Version

2024.06

### Operating System

Linux

### Description

Hi,

I am already a Mailu user and trying to switch to your OIDC fork to work with Authentik.
I have created a provider in Authentik already.
My mailu-OIDC settings are the following:

```
OIDC_ENABLED=true
OIDC_PROVIDER_INFO_URL=https://auth.REDACTED.com/application/o/mailu/
OIDC_CLIENT_ID=REDACTED
OIDC_CLIENT_SECRET=REDACTED
OIDC_BUTTON_NAME=SSO Account
OIDC_REDIRECT_URL=https://mail.REDACTED.com
OIDC_CHANGE_PASSWORD_REDIRECT_ENABLED=false
```
My Authentik instance is at `auth.REDACTED.com` and my mailu instance is at `mail.REDACTED.com`.

When trying to connect with OIDC, I get an HTTP error 400 on the following URL:
```
https://auth.REDACTED.com/application/o/authorize/?client_id=RmKuNWfnx8gfzhu5B5cNGD98qSScDjGtC1Sv7MdX&response_type=code&scope=openid+email&nonce=9KZQ0rio426RblTr&redirect_uri=https%3A%2F%2Fmail.REDACTED.com%2Fsso%2Flogin&state=HOozVCdZoGxcfa4K
```
This error happens before I get redirected to Authentik, right after clicking the SSO button.

If I compare with another web app that I am using with OIDC and Authentik, I have the following URL that works:
```
https://auth.REDACTED.commail/application/o/authorize/?response_type=code&state=KtpfMUULU-_E7NLcCe53vQ&code_challenge=oIM65KifavyxN09a-UgRcObyKh27HqbUDQIuUmY9KKE&code_challenge_method=S256&client_id=EJrZXnmFY9WFVDJdW0p4pgXBNUVDbIscjwKPWBx2&scope=openid profile groups&redirect_uri=https://stream.REDACTED.com/sso/OID/redirect/Authentik
```

My guess is that there is a problem with this URL but I am new with OIDC so I'm not sure.
Either way, what I don't understand is that you don't give a Redirect URL, where the OIDC provider should redirect the request to after authenticating. All OIDC apps I have have a redirect URI (in the case of the one shown above, `https://stream.REDACTED.com/sso/OID/redirect/Authentik`). What is it for Mailu OIDC ? Simply `https://mail.REDACTED.com` ?

Any answer is welcome, have a nice day !

### Replication Steps

1. Use Authentik
2. Set up provider for Mailu OIDC
3. Set Mailu OIDC settings
4. Try to connect

### Observed Behaviour

I get a 400 error on connection

### Expected Behaviour

I should get redirect to Authentik to connect.

**Comment by Encotric** [comment]
Hi, the redirect url is specified in the HTTP request to your Authentik server. In your example, you can see that there is a query parameter `redirect_uri=https%3A%2F%2Fmail.REDACTED.com%2Fsso%2Flogin`. Therefore, the redirect url is `https://mail.REDACTED.com/sso/login`. Unfortunately, I am unable to reproduce this issue. We use Authentik as well and never had such a problem in the past. 
Maybe you could post some log entries of your Mailu server regarding the HTTP 400 error? For me, it seems like this error is occuring on Authentik, not Mailu.

**Comment by LeVraiRoiDHyrule** [comment]
My problem was the redirect url. Now set to `https://mail.REDACTED.com/sso/login`, it works perfectly even with PKCE. Thanks for your help !

I would have a question about account creation via OIDC. Let's say I have an account in Authentik with username `USER42` and an email `sandwich@outlook.com`. When I logged in with this user to mailu, OIDC added the new domain `outlook.com` in addition to the already existing `redacted.com` and added directly `sandwich@outlook.com` as the new user.
Is it possible instead to have mailu OIDC to create new accounts based on the username with the existing domain, in this example creating the account `USER42@redacted.com` ?

**Comment by Encotric** [comment]
Unfortunately, that is not possible at the moment. Currently, we use the OIDC email to create a new mailu user. But maybe this could be a nice feature in the future - @Wombosvideo what do you think?

I guess we could add this idea to our project board, thank you!

**Comment by Wombosvideo** [comment]
@LeVraiRoiDHyrule I am not sure if I understand you correctly. **Please confirm** if this is what you want to see happening:

### Current Behaviour

- You already have a user account in Authenik with the username with the following details:

   | Key | Value |
   | --- | ----- |
   | username | `USER42` |
   | email | `sandwich@outlook.com` |

- When logging in to Mailu-OIDC with this account for the first time, Mailu-OIDC creates a new user account using the email `sandwich@outlook.com`, and adds `outlook.com` as a new domain.

### Desired Behaviour

- When logging in to Mailu-OIDC with this account for the first time, Mailu-OIDC creates a new user account and associates it with the existing domain `redacted.com`, resulting in a `USER42@redacted.com` mailbox.
- This allows you to log in to Authenik (and Mailu-OIDC) with an Outlook email address, but also allows you to send emails from your own domain.

**Comment by Wombosvideo** [comment]
To better keep track of issues, I will move this conversation to a new issue. This issue will be closed due to being resolved.

**Comment by LeVraiRoiDHyrule** [comment]
Hi,
Sorry for the late answer.

Yes, that is exactly the desired behaviour.
The finality of this would be that `USER42` is registered on Authentik with its own email address in a third party provider (in this example, `outlook.com`) that is verified by Authentik. He would get a new email address in Mailu's domain based on his username that he can use however he wants.

Maybe there could be those additional env variable:
`USER_CREATION_FROM_SCOPE` (yes/no), default yes
`USER_CREATION_SCOPE` (string), default "email". (is used only if `USER_CREATION_FROM_SCOPE=yes`)
`USER_CREATION_DOMAIN` (string), default "". (is used only if `USER_CREATION_FROM_SCOPE=no`)
`USER_CREATION_USERNAME_SCOPE` (string), default "username". (is used only if `USER_CREATION_FROM_SCOPE=no`)
